//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPISODE
    {
        public int epID { get; set; }
        public string epURL { get; set; }
        public Nullable<int> epNum { get; set; }
        public Nullable<int> movie_ID { get; set; }
    
        public virtual MOVIE MOVIE { get; set; }
    }
}
