//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.EPISODES = new HashSet<EPISODE>();
            this.USERS = new HashSet<USER>();
        }
    
        public int movieId { get; set; }
        public string movieName { get; set; }
        public string movieThumb { get; set; }
        public string movieDes { get; set; }
        public Nullable<int> movieView { get; set; }
        public Nullable<int> movieStatus { get; set; }
        public Nullable<int> movieGenre { get; set; }
        public string movieURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPISODE> EPISODES { get; set; }
        public virtual GENRE GENRE { get; set; }
        public virtual MOVSTATU MOVSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
