//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userPass { get; set; }
        public string userRole { get; set; }
        public Nullable<int> userLikeMov { get; set; }
        public Nullable<int> userType_ID { get; set; }
    
        public virtual MOVIE MOVIE { get; set; }
        public virtual USERTYPE USERTYPE { get; set; }
        [NotMapped]
        [Compare("userPass")]
        public string userRepass {  get; set; }
    }
}
